#!/bin/bash
# Get Railway PostgreSQL Public URL Helper

echo "🔍 Getting Railway PostgreSQL Public URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Your Railway CLI is linked to project: PUSHIN"
echo ""
echo "To get your PUBLIC proxy URL (for local development):"
echo ""
echo "METHOD 1: Via Railway Dashboard (EASIEST) ⭐"
echo "  1. Go to: https://railway.app/dashboard"
echo "  2. Click on project 'PUSHIN'"
echo "  3. Click on 'PostgreSQL' service (database icon)"
echo "  4. Click 'Connect' tab"
echo "  5. Copy 'Postgres Connection URL' - looks like:"
echo "     postgresql://postgres:PASSWORD@something.proxy.rlwy.net:PORT/railway"
echo "     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "     This is the PUBLIC proxy URL you need!"
echo ""
echo "METHOD 2: Via Railway CLI (if database plugin exists)"
echo "  Run: railway variables | grep DATABASE_URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ WRONG URL (you have this now - won't work locally):"
echo "   postgresql://...@postgres-zvno.railway.internal:5432/railway"
echo "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "                     Internal hostname - only works inside Railway"
echo ""
echo "✅ CORRECT URL (what you need):"
echo "   postgresql://...@something.proxy.rlwy.net:PORT/railway"
echo "                     ^^^^^^^^^^^^^^^^^^^^^^^^"
echo "                     Public proxy - works everywhere"
echo ""
