#!/bin/bash
# Database Environment Setup Script
# Creates .env file for local development

echo "🔧 Setting up database environment for local development"
echo ""

# Check if .env already exists
if [ -f .env ]; then
  echo "⚠️  .env file already exists!"
  read -p "Do you want to overwrite it? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Setup cancelled"
    exit 1
  fi
fi

# Get Railway connection string
echo "📋 You need your Railway PostgreSQL connection string"
echo ""
echo "Get it from:"
echo "  1. Go to Railway Dashboard"
echo "  2. Select your project"
echo "  3. Click PostgreSQL service"
echo "  4. Click 'Connect' tab"
echo "  5. Copy the 'Postgres Connection URL' (public proxy)"
echo ""
echo "Example format:"
echo "  postgresql://postgres:PASSWORD@HOST.proxy.rlwy.net:PORT/railway"
echo ""

read -p "Enter your DATABASE_URL: " database_url

if [ -z "$database_url" ]; then
  echo "❌ DATABASE_URL cannot be empty"
  exit 1
fi

# Validate URL format
if [[ ! $database_url =~ ^postgresql:// ]]; then
  echo "❌ Invalid URL format. Must start with postgresql://"
  exit 1
fi

# Create .env file
cat > .env << EOF
# Local Development Environment Variables
# Generated by setup-database-env.sh

# Railway PostgreSQL Connection
DATABASE_URL=$database_url

# Note: On Railway deployment, these are auto-set:
# - DATABASE_PRIVATE_URL (preferred, internal network, no SSL)
# - DATABASE_URL (fallback, external proxy, SSL)
EOF

echo ""
echo "✅ Created .env file successfully!"
echo ""
echo "🚀 Next steps:"
echo "  1. npm install          # Install dependencies"
echo "  2. npm run db:create    # Create database tables"
echo ""
