// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmM7nVtbNWjQTgmN5KUhJ_lbCo_3X90I',
    appId: '1:295186904898:web:31b8eddf007453bc30badb',
    messagingSenderId: '295186904898',
    projectId: 'pushin-auth',
    authDomain: 'pushin-auth.firebaseapp.com',
    storageBucket: 'pushin-auth.firebasestorage.app',
    measurementId: 'G-Q4PJQGPFTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgDRjAH7Wz31UT9XJCUyQQXxHYDmCr3HM',
    appId: '1:295186904898:android:15ccec1d194c261030badb',
    messagingSenderId: '295186904898',
    projectId: 'pushin-auth',
    storageBucket: 'pushin-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvMu5_6YVg3d_n1tyjEozyW_X6qQEGWXs',
    appId: '1:295186904898:ios:1f96efd748dfc42130badb',
    messagingSenderId: '295186904898',
    projectId: 'pushin-auth',
    storageBucket: 'pushin-auth.firebasestorage.app',
    iosClientId: '295186904898-tt9hae40m8v0l5b021cv008995a3eck7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushinReload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvMu5_6YVg3d_n1tyjEozyW_X6qQEGWXs',
    appId: '1:295186904898:ios:1f96efd748dfc42130badb',
    messagingSenderId: '295186904898',
    projectId: 'pushin-auth',
    storageBucket: 'pushin-auth.firebasestorage.app',
    iosClientId: '295186904898-tt9hae40m8v0l5b021cv008995a3eck7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushinReload',
  );
}
